### ISSUE TITLE
CPIO  header corrupted

### ISSUE THREAD

**Issue by zfxw0206** [lovepark/o3d3xx-firmware#1]
Now I want to update the firmware of my O3D303 to Goldeney_1.6.2038. But after I choose the fireware, I got the ERROR:  "CPIO Header corrupted, cannot be parsed. Image invalid or corrupted. Not installing ...".

Does anybody know what does this mean? How can I solve the problem? Thank you!

**Comment by tpanzarella** [comment]
Did you validate the checksum?

**Comment by tpanzarella** [comment]
Also, official firmware images can be acquired from: http://www.ifm.com/ifmus/web/dualis-download.htm

**Comment by zfxw0206** [comment]
How to validate the checksum?

**Comment by tpanzarella** [comment]
There is a file called [checksums.md5](https://github.com/lovepark/o3d3xx-firmware/blob/master/checksums.md5) in the repository. It maps a firmware archive to its MD5 checksum. On your local machine, you can run `md5sum` against the downloaded firmware archive. The checksums should be consistent.

**Comment by tpanzarella** [comment]
Also, per the [README](https://github.com/lovepark/o3d3xx-firmware/blob/master/README.md), make sure you have [git large file storage](https://git-lfs.github.com/) support built into your git before cloning. Or, just [download](http://www.ifm.com/download/files/ifm-O3D3xx_FW_1_6_2038/$file/ifm-O3D3xx_FW_1_6_2038.zip) from IFM. The checksum should still be consistent.

**Comment by zfxw0206** [comment]
Yes, I download from IFM, it is working. Thank you!
